# Generated by Django 4.2.3 on 2026-07-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='course',
            new_name='question',
        ),
    ]
